# User config
author: "Avsey Games"
tagline: "Games Developed"
description: "Indies project"
keywords: "Game, Android"
email: "avseygames@gmail.com"
linkedin: 
twitter: 
github: 

# Site config
baseurl: "avseygames.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
